### ISSUE TITLE
Components to build the prosthetic hands

### ISSUE THREAD

**Issue by jokla** [OpenBionics/Prosthetic-Hands#5]
Hi!

I am looking for the components to buy (I am in France now). 

I would have some questions:
1) Is [this list](https://hackaday.io/project/4745/components) updated?
2) About the [Prosthetic board](https://github.com/OpenBionics/Prosthetic-Hands/tree/master/Electronics). I don't have experience with PCB. Is it possible to buy it somewhere? Otherwise, could you give me some tips to build it?
3) About the Surface electromyography sensing kit: is the new [MyoWare Muscle Sensor](http://www.exp-tech.de/myoware-muscle-sensor) working ? or is it necessary to buy the [old version](http://www.exp-tech.de/sparkfun-ad8232-single-lead-heart-rate-monitor)?
4) Are this [Arduino micro ](http://www.exp-tech.de/arduino-micro) and [this motor](http://www.francerobotique.com/servomoteurs-intelligents/176-herkulex-drs-0201.html) ok? 

Thank you very much in advance!

**Comment by gkontoudis** [comment]
Hello,

Thank you for your interest in our prosthetic hands.

1. Yes it is, but you can use any servo motor and any micro-controller works best for you. You can also check our [Assembly Guide](https://github.com/OpenBionics/Prosthetic-Hands/blob/master/Assembly%20Guide/tex/OpenBionics_ProstheticHandsGuide2015.pdf).
2. The files that you need in order to build the PCB are provided on this [page](https://github.com/OpenBionics/Prosthetic-Hands/tree/master/Electronics). If you face any difficulties, you could skip the PCB building and control the hand directly with the micro-controller. You can find many ways to implement it with respect to the servo motor you plan to use.
3. All versions are working properly, but I suggest you the new version which I also use.
4. You can choose any servo motor and any micro-controller you want.
